name: Build and Release Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1.1

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        env:
          CXXFLAGS: "/std:c++20 /await /EHsc"
          CMAKE_CXX_FLAGS: "/std:c++20 /await /EHsc"
        run: |
          flutter config --enable-windows-desktop
          flutter clean
          flutter build windows --release --verbose

      - name: Archive Windows build
        run: |
          cd build\windows\x64\runner\Release
          7z a DigitalScale-Windows.zip *
      - name: Publish to GitHub Releases
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/x64/runner/Release/DigitalScale-Windows.zip
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
