name: Build and Release macOS and Windows Apps

on:
  push:
    branches:
      - main   # 触发构建的分支
  pull_request:
    branches:
      - main   # 对主分支的 PR 进行构建

jobs:
  build-macos:
    runs-on: macos-latest  # 使用 macOS 环境

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies with Homebrew
        run: |
          brew install automake
          brew install libtool

      - name: Install dependencies
        run: flutter pub get  # 安装项目依赖

      - name: Build macOS app
        run: flutter build macos --release  # 构建 macOS 应用

      - name: Archive macOS build
        run: |
          cd build/macos/Build/Products/Release
          zip -r DigitalScale-macOS.zip DigitalScale.app

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/macos/Build/Products/Release/DigitalScale-macOS.zip
          token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest  # 使用 Windows 环境
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get  # 安装项目依赖

      - name: Install dependencies using choco
        run: |
          choco install cmake --version=3.21.2
          choco install visualstudio2019-workload-vctools

      - name: Build Windows application
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="/std:c++20"

      - name: Compile the project
        run: |
          cmake --build build --config Release

      - name: Build Windows app
        run: flutter build windows --release  # 构建 Windows 应用

      - name: Archive Windows build
        run: |
          cd build/windows/runner/Release
          tar -a -c -f DigitalScale-Windows.zip DigitalScale.exe

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/runner/Release/DigitalScale-Windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}
