name: Build and Release macOS and Windows Apps

on:
  push:
    branches:
      - main   # 触发构建的分支
  pull_request:
    branches:
      - main   # 对主分支的 PR 进行构建
  create:  # 监听标签创建事件
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest  # 使用 macOS 环境

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保可以获取所有标签

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies with Homebrew
        run: |
          brew install automake
          brew install libtool

      - name: Install dependencies
        run: flutter pub get  # 安装项目依赖

      - name: Build macOS app
        run: flutter build macos --release  # 构建 macOS 应用

      - name: Archive macOS build
        run: |
          cd build/macos/Build/Products/Release
          zip -r DigitalScale-macOS.zip DigitalScale.app

      - name: Get tag name
        id: get_tag_name
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Publish to GitHub Releases
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/macos/Build/Products/Release/DigitalScale-macOS.zip
          tag_name: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保可以获取所有标签

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get  # 安装项目依赖

      - name: Build Windows app
        run: flutter build windows --release  # 构建 Windows 应用

      - name: Archive Windows build
        run: |
          cd build/windows/runner/Release
          7z a DigitalScale-Windows.zip ./*  # 使用 7z 替代 tar 命令，打包所有必要文件

      - name: Get tag name
        id: get_tag_name
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Publish to GitHub Releases
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/runner/Release/DigitalScale-Windows.zip
          tag_name: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
