name: Build and Release macOS and Windows Apps

on:
  push:
    branches:
      - main   # 触发构建的分支
  pull_request:
    branches:
      - main   # 对主分支的 PR 进行构建
  create:  # 监听标签创建事件
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest  # 使用 macOS 环境

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保可以获取所有标签

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies with Homebrew
        run: |
          brew install automake
          brew install libtool

      - name: Install dependencies
        run: flutter pub get  # 安装项目依赖

      - name: Build macOS app
        run: flutter build macos --release  # 构建 macOS 应用

      - name: Archive macOS build
        run: |
          cd build/macos/Build/Products/Release
          zip -r DigitalScale-macOS.zip DigitalScale.app

      - name: Get tag name
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        id: get_tag_name
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Using tag: ${GITHUB_REF#refs/tags/}"

      - name: Publish to GitHub Releases
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/macos/Build/Products/Release/DigitalScale-macOS.zip
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

  build-windows:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保可以获取所有标签

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1.1

      - name: Install dependencies
        run: flutter pub get  # 安装项目依赖

      - name: Clean build directory
        run: |
          if exist build rd /s /q build
        shell: cmd

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/std:c++20 /await /EHsc"
        working-directory: windows

      - name: Build Windows app
        env:
          CXXFLAGS: "/std:c++20 /await /EHsc"
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Archive Windows build
        run: |
          cd build/windows/runner/Release
          7z a DigitalScale-Windows.zip ./*  # 使用 7z 替代 tar 命令，打包所有必要文件

      - name: Get tag name
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        id: get_tag_name
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Using tag: ${GITHUB_REF#refs/tags/}"
        shell: bash

      - name: Publish to GitHub Releases
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/runner/Release/DigitalScale-Windows.zip
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
